### ISSUE TITLE
Compatibility with stripe-php version 7

### ISSUE THREAD

**Issue by acabrkic** [wagnerwagner/merx#16]
Hello, we are using PHP 7.4 and when we install merx 1.4.0 rc-1 via composer, it says that it is compatible only with stripe-php packages 6.28^ and not compatible with php-stripe 7. This is not a big problem, but there is a line in ApiRequestor.php (line 402) that uses `array_key_exists('request-id', $rheaders)` and this does not work in php 7.4 as $rheaders is an object, so it is necessary to say `(array)$rheaders` . This is fixed in stripe-php 7. 

Will merx be compatible with stripe-php ^7.0 soon?

**Comment by vitamin2ag** [comment]
looking also forward to this.

**Comment by tobiasfabian** [comment]
Thanks for your feedback.

I’ll look into that this week.

**Comment by acabrkic** [comment]
https://github.com/stripe/stripe-php/issues/827 this is the link to the problem, sorry I forgot to mention it

**Comment by tobiasfabian** [comment]
Hey @acabrkic and @vitamin2ag,

I’ve upgraded the stripe composer module to 7.22 and experienced no issues. There is a pre-release:
https://github.com/wagnerwagner/merx/releases/tag/1.4.1-rc.1

**Comment by acabrkic** [comment]
@tobiasfabian This fixed it, thank you :)
