### ISSUE TITLE
Currency symbol before number

### ISSUE THREAD

**Issue by guidoferreyra** [wagnerwagner/merx#2]
Hi! I was looking the code of Merx to set the symbol before the number, and I found that is related with localeconv(), but sometimes this is not desired. Maybe it will be better to configure this via config options.

Here a demo code, maybe explain better what I’m thinking.

```
   public static function formatPrice(float $price): string
    {
        $localeFormatting = localeconv();
        $precedes = option('ww.merx.currencySymbolBefore', true);
        $string = '';
        if ($precedes) {
            $string .= option('ww.merx.currencySymbol', '€');
            if (option('ww.merx.currencySpace')) {
                $string .= ' '; // non breaking space
            }
        }
        $string .= number_format($price, 2, $localeFormatting['decimal_point'] ?? '.', $localeFormatting['thousands_sep'] ?? ',');
        if (!$precedes) {
            if (option('ww.merx.currencySpace')) {
                $string .= ' '; // non breaking space
            }
            $string .= option('ww.merx.currencySymbol', '€');
        }
        return $string;
    }
```

**Comment by tobiasfabian** [comment]
I’ve updated the formatPrice function with the [latest release](https://github.com/wagnerwagner/merx/releases/tag/1.2.3). What do you think. Is this everything you need?

https://merx.wagnerwagner.de/docs/classes/merx#formatprice

**Comment by guidoferreyra** [comment]
Looks great, I will try it. Thanks a lot!

**Comment by guidoferreyra** [comment]
Hi Tobiaas, what do you think on adding an argument to control the number of decimals?
