### ISSUE TITLE
Conditional taxes, taxes variations

### ISSUE THREAD

**Issue by plagasul** [wagnerwagner/merx#22]
Hello,

According to my EU based client, he oly needs to charget VAT to EU customers, but no VAT to non-EU customers.

How can this be handled in merx?

Could I for example overwrite the tax on cart->add() as suggested in the product variations cookbook for price ?

Danke

**Comment by plagasul** [comment]
Actually, according to documentation and my own test, product price is supposed to be introduced TAX INCLUDED ?

If I am correct, that seems to complciate tax variation.

I don't have much experience with web stores, but wouldn't it be more flexible to specify a product's base price and tax rate separatedly? and calculate total price from there ?

Or am I missing something ?

**Comment by tobiasfabian** [comment]
Hey @plagasul,

Merx is a _basic_ toolkit to build shops. Conditional taxes are not supported as a core feature, sorry. But. You can build it by your own. In fact [merx.wagnerwagner.de](https://merx.wagnerwagner.de) updates the price depending on the country you select. If the user selects Germany the VAT is added to the price of the license.

Here is the code for this feature: https://github.com/wagnerwagner/merx.wagnerwagner.de/blob/master/site/plugins/site/index.php#L183-L189

**Comment by plagasul** [comment]
That is very useful, much appreciated.
