### ISSUE TITLE
Additional product blueprint

### ISSUE THREAD

**Issue by plagasul** [wagnerwagner/merx#23]
Would it be possible to use a blueprint different than product.txt that would still be reccognized by MERX as a product?

Different products may have different panel form needs. In particular 'Shipping', as product, differs quite a lot to any other regular product, and would help to provide a specific blueprint for it.

As a workaround conditional fields may be used, and we can organize shipping products under a subpage, but still a workaround.

If this cannot be done, I believe it is a good feature to add.

Danke

**Comment by tobiasfabian** [comment]
Hey @plagasul,

since [1.3.0](https://github.com/wagnerwagner/merx/releases/tag/1.3.0) every template can be added to the cart as long as the page has a `price` field.

**Comment by plagasul** [comment]
I see the feature on the list now, great! thank you @tobiasfabian
