### ISSUE TITLE
$productList empty

### ISSUE THREAD

**Issue by alexpi** [wagnerwagner/merx#24]
Hello,

I have the following content structure:
```
content/
  products/
    1_598879/
      product.el.txt
      product.en.txt
```
product.el.txt:
```txt
Title: 598879
----
Price: 10.00
----
Tax: 24
...
```
If I log $productList, it is empty. Am I missing some requirement for pages to be listed as products?

**Comment by tobiasfabian** [comment]
Hey @alexpi,

Merx does not provide a tool to show all products. You can use `$site->index()->template('product')` to list all _products_ of your shop.
  
[`ProductList`](https://merx.wagnerwagner.de/docs/classes/productlist) is the base of [`Cart`](https://merx.wagnerwagner.de/docs/classes/cart). To learn how to use $productList I recommend the [Wishlist Cookbook](https://merx.wagnerwagner.de/cookbooks/wishlist).
