### ISSUE TITLE
initializePayment() returns memory error

### ISSUE THREAD

**Issue by alexpi** [wagnerwagner/merx#26]
I am trying to integrate Stripe payments with Merx.
I used the exact same code from the example at https://merx.wagnerwagner.de/cookbooks/checkout-with-stripe-s-payment-intents, but as soon as the initializePayment() function is called, the error "Allowed memory size of 134217728 bytes exhausted (tried to allocate 143360 bytes)", is returned. Am I missing something?
```php
'pattern' => 'shop-api/submit',
'method' => 'POST',
'action' => function() {
  try {
    $data = [
      'paymentMethod' => 'credit-card-sca',
      'email' => 'chuck@example.com',
      'name' => 'Chuck Norris',
    ];

    $paymentIntentId = kirby()->session()->get('paymentIntentId');
    
    $data = array_merge($data, [
      'stripePaymentIntentId' => $paymentIntentId,
    ]);

    $redirect = merx()->initializePayment($data);
    
    return [
      'status' => 201,
      'redirect' => url($redirect),
    ];
  } catch (Kirby\Exception\Exception $ex) {
    return $ex->toArray();
  }
},
```

**Comment by alexpi** [comment]
The problem was indeed that PHP's memory size was not sufficient. Sorry!

**Comment by alexpi** [comment]
It worked after increasing memory, but I am getting the error again.

**Comment by tobiasfabian** [comment]
Hey @alexpi,

I’m sorry, I can’t reproduce your issue.

Here are a few things you can try.

- Do you set the `paymentIntentId` sometime before `shop-api/submit` is called?
```php
$paymentIntent = $cart->getStripePaymentIntent($params);
kirby()->session()->set('paymentIntentId', $paymentIntent->id);
```
- Does it work with version [1.4.1](https://github.com/wagnerwagner/merx/tree/1.4.1)? 
- Does it work with the latest commit (06157107864ff8e7a7b028b3c55cd1a37c55a96e) in the develop branch?
- Deactivate other plugins.
- What Kirby version do you use?
- Wild guess. Maybe the sessions are getting very big. Can you have a look at the files in `site/sessions/`.

**Comment by alexpi** [comment]
It was my mistake after all. I was adding a shipping product, and instead of adding its ```id```, to the cart, I was sending the whole shipping product file. Sorry for the trouble and thanks for your help!
