### ISSUE TITLE
Composer Package

### ISSUE THREAD

**Issue by guidoferreyra** [wagnerwagner/merx#3]
Hi! Is possible to install Merx via Composer? Best

**Comment by tobiasfabian** [comment]
No, it’s not (yet) possible. We want to keep it as simple as possible first.

Do you need a composer setup?

**Comment by guidoferreyra** [comment]
In the site I’m developing with Merx I just changed to composer and I found that is very helpful, is my first time with it. I think I can make it work Merx with composer just using the custom repositories option but is cloning it to a vendor folder instead site/plugins.

**Comment by tobiasfabian** [comment]
Added with [1.3.0](https://github.com/wagnerwagner/merx/releases/tag/1.3.0)
✌️
