### ISSUE TITLE
product sample text in docs is indented by one space

### ISSUE THREAD

**Issue by scsskid** [wagnerwagner/merx#32]
this causes, all contents to be treated as part of title

https://merx.wagnerwagner.de/docs/getting-started/add-products

i though my install is broken, maybe this can put some people off, at this early stage of explore your software

also in blueprint sample, there is no field type description in kirby nativly, I get error, I suppose should be texarea, otherwise a custom field type by merx isnt working for me

**Comment by tobiasfabian** [comment]
Thanks I fixed both.
