### ISSUE TITLE
formatPrice() doesn't seem to insert a thousands separator 

### ISSUE THREAD

**Issue by leuys** [wagnerwagner/merx#4]
The `formatPrice()` function doesn't seem to insert a thousands separator, even when locality is set to German.
Maybe it would be also be possible to have a config option, as with `ww.merx.currencyPositionPrecedes` for example. 

Something like:
`'ww.merx.currencyThousandsSeparator' => '.'`

Excerpt of the options currently set in my `config.php`:

`'locale' => 'de_DE.utf-8',`
`'ww.merx.currency' => 'EUR',`
`'ww.merx.currencySymbol' => '€',`
`'ww.merx.currencySeperateBySpace' => true,`
`'ww.merx.currencyPositionPrecedes' => false,`

**Comment by tobiasfabian** [comment]
83e33145a13e0e51e84a98dcf1981e10cf5c3ed1

**Comment by tobiasfabian** [comment]
I’ve added this option to the [latest beta](https://github.com/wagnerwagner/merx/releases/tag/1.3.0-beta).
