### ISSUE TITLE
Improve price field for `Page must have a price field.` error

### ISSUE THREAD

**Issue by afbora** [wagnerwagner/merx#40]
Getting following error when you use calculated price on product models.

> `Page must have a price field.`

https://github.com/wagnerwagner/merx/blob/master/src/Cart.php#L47

Can be use `isNotEmpty()` method instead of `exists()`

````php
} elseif (!$page->price()->isNotEmpty()) {
  throw new \Exception('Page must have a price field.');
}

**Comment by tobiasfabian** [comment]
Hey @afbora,

I removed the price check for product pages. This should solve your problem. You can try it with [1.6.0-beta.2](https://github.com/wagnerwagner/merx/releases/tag/1.6.0-beta.2).
