### ISSUE TITLE
Compatibility issue with Kirby 3.7.1

### ISSUE THREAD

**Issue by xavierfoucrier** [wagnerwagner/merx#52]
Hello Merx team :wave: 

We recently moved to Kirby 3.7.1 and noticed an issue in the backend when accessing orders:

![image](https://user-images.githubusercontent.com/2471223/180994782-6d6ea484-cf32-42b0-96e3-adc931c1b7b1.png)

> See **Refactoring** section here for more informations: https://github.com/getkirby/kirby/releases/tag/3.7.1.

**Comment by bnomei** [comment]
i can second that issue. related to kirby collections `__set` returning `self` instead of `void` like the core class does.

**Comment by xavierfoucrier** [comment]
@bnomei thanks! :sun_with_face:

**Comment by tobiasfabian** [comment]
Thank you all for your comments.

It’s fixed in [1.6.1](https://github.com/wagnerwagner/merx/releases/tag/1.6.1)

**Comment by xavierfoucrier** [comment]
Thanks a lot @tobiasfabian, we will update it soon! :wink:
