### ISSUE TITLE
Is it possible to disable online payments?

### ISSUE THREAD

**Issue by RiseCreativeStudio** [wagnerwagner/merx#53]
Hi I'm wondering if it's possible to disable online payments? I want customers to make an order online, but they have to pay in a shop. Can't find it in the documentation.

Thanks in advance!

**Comment by tobiasfabian** [comment]
Yes, that’s possible. You can create an empty [custom payment gateway](https://merx.wagnerwagner.de/cookbooks/custom-payment-gateways) called e.g. “shop-payment” or “offline-payment”.

The [Merx Starterkit](https://github.com/wagnerwagner/merx-starterkit) comes with an empty custom payment gateway ([config/config.php](https://github.com/wagnerwagner/merx-starterkit/blob/main/site/config/config.php#L52-L54)). You can duplicate the Starterkit and remove all other payment methods [(snippets/payment-methods.php)](https://github.com/wagnerwagner/merx-starterkit/blob/main/site/snippets/payment-methods.php) from the checkout page ([templates/checkout.php](https://github.com/wagnerwagner/merx-starterkit/blob/main/site/templates/checkout.php))
