### ISSUE TITLE
Upgrade to Paypal API v2

### ISSUE THREAD

**Issue by xavierfoucrier** [wagnerwagner/merx#56]
Hello merx team!

In order to keep dependencies as up to date as possible, it would be very nice if you could **upgrade to the Paypal API v2**.
Does this mean a lot of code refactoring on your side?

Thanks! :wink:

**Comment by lassereinboeng** [comment]
Hi @tobiasfabian,

I would love to use merx for a client project (as I think it's a great plugin!) but the deprecated PayPal SDK is a little deterrent. And the budget might be too small for integrating the new PayPal API via a custom payment provider.
Do you plan to upgrade the PayPal integration in the near future (like in the next couple months)? That would be awesome!

Thanks and have a great weekend :-)

**Comment by tobiasfabian** [comment]
We are now working on the upgrade. Hopefully we can release a new version in a few weeks.

**Comment by xavierfoucrier** [comment]
Thanks @tobiasfabian for the feedback 👍 
Feel free to close the issue when it's done 😎

**Comment by tobiasfabian** [comment]
Fixed in [1.8.0-beta.1](https://github.com/wagnerwagner/merx/releases/tag/v1.8.0-beta.1)

**Comment by xavierfoucrier** [comment]
Thanks @tobiasfabian 😉
