### ISSUE TITLE
Wagnerwagner\Merx\ProductList::__set(): Return type must be void when declared

### ISSUE THREAD

**Issue by jm1994** [wagnerwagner/merx#57]
Hey,
in merx-plainkit\site\plugins\merx\src\productList.php line 82 (public function __set(string $key, $value): self) it says:

> Wagnerwagner\Merx\ProductList::__set(): Return type must be void when declared. 

Maybe because I'm on the latest php version? 8.1.4?

**Comment by tobiasfabian** [comment]
Which version of Merx do you use? This issue should be fixed in [1.6.1](https://github.com/wagnerwagner/merx/releases/tag/1.6.1).

**Comment by jm1994** [comment]
1.0.0-beta.1 I guess. Was getting started with the plainkit. Guess I have to update... will try.
