### ISSUE TITLE
How do you add different types of sizes for a product?

### ISSUE THREAD

**Issue by Tazi0** [wagnerwagner/merx#59]
I've gone so far as making a structure as a field, show the options on the front-end and add the chosen size to the order. But when trying with multiple sizes. The `Cart` object adds the different sizes together (while they should be separated) and thus merging the sizes and causing an issue. How do you separate the cart items?

**Comment by tobiasfabian** [comment]
You need to add an additional `key` to the `$cart-add()` method as described here https://merx.wagnerwagner.de/cookbooks/product-variants#add-to-cart.

Does this solve your issue?

**Comment by Tazi0** [comment]
it does, thanks!
