### ISSUE TITLE
Deprecated Stripe API

### ISSUE THREAD

**Issue by Tazi0** [wagnerwagner/merx#60]
I've noticed that Merx still uses the deprecated [sources API](https://stripe.com/docs/sources) for their SEPA Direct Debit payments. Which Stripe doesn't recommend using and businesses based in the [European Economic Area](https://en.wikipedia.org/wiki/European_Economic_Area) (EEA) should follow the regulations and not use this outdated API. 

Any way of upgrading?

**Comment by tobiasfabian** [comment]
I have finally replaced the sources API with Payment Intents.

Thank you for your patience.

Fixed in [1.9.0-beta.1](https://github.com/wagnerwagner/merx/releases/tag/v1.9.0-beta.1)
