### ISSUE TITLE
Cart and Checkout problem

### ISSUE THREAD

**Issue by vivaneo** [wagnerwagner/merx#65]
Hi,

I have a problem with Checkout (on payment validation). Other people have a problem with the display of the basket.

Kirby 3.8.1.1
PHP 8

The tests were done in localhost and online.

https://forum.getkirby.com/t/merx-starterkit-e-commerce-cart-problem/25310/11

**Comment by tobiasfabian** [comment]
Hi @vivaneo,

I don't quite understand what exactly the issue is.
Has it something to do with `tax()`? Or do you have a problem with `JSON.parse`?
