### ISSUE TITLE
Merx and Kirby4

### ISSUE THREAD

**Issue by matzebuchholz** [wagnerwagner/merx#74]
Hi there,

i have a Kirby4-Page and tried to install MERX via composer (I'm really new at working with composer)
the installation worked, but composer downgraded my kirby to 3.10 in the installation routine.
the Kirby-plugin-page says Merx is kompatible with Kirby4.

So please tell me how I can install Merx with Kirby 4.

Thanks a lot,
Matthias

**Comment by tobiasfabian** [comment]
Hi Matthias,

I tried to replicate your issue – without success.
Here is what I did:

- Downloaded Kirby Starterkit.
- Installed Merx via Composer `composer require wagnerwagner/merx`.

Merx and Kirby (Version 4) run without any issues.

The `composer.json` looks like this:

```json
…
  "require": {
    "php": "~8.1.0 || ~8.2.0 || ~8.3.0",
    "getkirby/cms": "^4.0",
    "wagnerwagner/merx": "^1.7"
  },
…
```

What does your `composer.json` looks like? Did you installed Kirby via Composer? Did you upgraded your site from Kirby 3 to 4?

**Comment by sumpfi82** [comment]
Hi Tobias, I'm very sorry, I think it was my fault.
I'm new at working with composer, so the thing was: I have a Kirby-Installation which was made without Composer. I updated it to Kirby 4 (by changing the Kirby-folder) and than I did the Merx install.
Now I did it right: I made a new kirby-Projekt with composer and than installed Merx and I have Merx with Kirby4 now. :)

**Comment by kosmar** [comment]
i installed with compser into an existing kirby 4 and made the setup in models/order.php
debug tells me merx is looking for a cms/src/field.php which is not existing in kirby 4

see: https://forum.getkirby.com/t/src-cms-field-php-missing-since-4-0-0/30575

**Comment by tobiasfabian** [comment]
I tried different Merx/Kirby/Composer installations and never run into any issues, but maybe I am missing something.

Theoretically I can imagine that there might be some hiccups when you install Kirby without Composer and Merx with Composer (or the other way around). Could you please try to install Kirby and Merx with Composer or, alternately, remove composer and download the code from the release pages ([Kirby](https://github.com/getkirby/kirby/releases/tag/4.0.3)/[Merx](https://github.com/wagnerwagner/merx/releases/tag/v1.7.2)).

I also tested installation via git submodule, wich also works without any issues.

**Comment by kosmar** [comment]
the issue came from upgrading by downloading kirby folders and not
using composer for that,
so i edited my composer json and lock, ran it and i was kinda fine.

now looking at how to get merx doing a thing.
